In [1]:
import pandas as pd
import seaborn as sns
import seaborn.objects as so
import matplotlib.pyplot as plt
import numpy as np

import ipywidgets as widgets
from ipywidgets import interact

In [2]:
df = pd.read_csv('stroke.csv')

In [3]:
df_icu = df[df['ICU Checkout Time'].notna()]
df_icu

,Patient Id,Age,Gender,Comorbidities,Emergency Dept Time,Admission Time,Discharge Time,CT Scan Time,TPA Time,ICU Arrival Time,ICU Checkout Time,Neurology Ward Arrival Time,Occupational Therapist Visit,Speech Pathologist Visit,Physiotherapist Visit,Dietitian Visit,Social Worker Visit,Cardiologist Visit,Neurologist Visit
1,1,75,F,False,2023-01-04 23:20:00,2023-01-05 02:13:00,2023-01-10 10:59:00,2023-01-04 23:33:00,NaN,2023-01-05 02:14:00,2023-01-06 09:44:00,2023-01-06 09:44:00,NaN,2023-01-07 01:21:00,2023-01-05 03:13:00,NaN,2023-01-06 00:39:00,NaN,2023-01-06 06:17:00
2,2,50,M,False,2022-12-28 18:33:00,2022-12-29 03:20:00,2023-01-06 08:01:00,2022-12-28 18:47:00,NaN,2023-01-01 08:51:00,2023-01-02 22:15:00,2023-01-02 22:15:00,NaN,NaN,NaN,2023-01-06 07:42:00,2023-01-01 04:57:00,NaN,2022-12-29 22:37:00
9,9,58,M,False,2023-06-21 06:56:00,2023-06-21 16:16:00,2023-07-05 11:00:00,2023-06-21 07:06:00,NaN,2023-06-21 18:18:00,2023-06-24 03:17:00,2023-06-24 03:17:00,2023-06-21 18:56:00,NaN,NaN,2023-07-05 10:42:00,2023-06-28 21:08:00,NaN,2023-06-21 16:31:00
13,13,74,M,True,2023-06-30 09:26:00,2023-06-30 19:47:00,2023-07-16 11:11:00,2023-06-30 09:43:00,NaN,2023-06-30 21:34:00,2023-07-12 16:56:00,2023-07-12 16:56:00,2023-07-02 03:18:00,2023-07-01 15:22:00,2023-07-01 11:13:00,NaN,NaN,NaN,2023-06-30 23:17:00
14,14,92,M,False,2022-09-06 05:04:00,2022-09-06 10:17:00,2022-09-24 11:48:00,2022-09-06 05:18:00,NaN,2022-09-09 09:17:00,2022-09-18 08:59:00,2022-09-18 08:59:00,2022-09-08 00:58:00,NaN,2022-09-24 11:13:00,NaN,2022-09-07 23:57:00,NaN,2022-09-08 20:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5139,5139,70,F,False,2022-08-10 19:03:00,2022-08-10 23:34:00,2022-08-18 17:02:00,2022-08-10 19:15:00,2022-08-10 19:54:00,2022-08-11 14:41:00,2022-08-14 00:18:00,2022-08-14 00:18:00,2022-08-11 01:25:00,2022-08-18 16:26:00,2022-08-13 00:06:00,2022-08-12 20:43:00,NaN,NaN,2022-08-11 02:41:00
5142,5142,63,F,True,2022-05-28 16:56:00,2022-05-28 22:01:00,2022-06-10 05:52:00,2022-05-28 17:08:00,NaN,2022-05-28 22:29:00,2022-05-30 01:02:00,2022-05-30 01:02:00,2022-05-29 00:24:00,2022-05-29 04:57:00,NaN,2022-05-30 22:36:00,2022-06-03 22:25:00,2022-06-10 05:20:00,2022-06-04 15:42:00
5144,5144,87,M,True,2023-12-11 00:52:00,2023-12-11 04:36:00,2023-12-18 19:59:00,2023-12-11 01:04:00,NaN,2023-12-11 04:39:00,2023-12-13 18:35:00,2023-12-13 18:35:00,2023-12-11 05:25:00,NaN,2023-12-11 03:54:00,NaN,NaN,NaN,2023-12-12 03:03:00
5145,5145,69,F,False,2022-03-12 00:01:00,2022-03-12 07:49:00,2022-03-20 09:46:00,2022-03-12 00:14:00,NaN,2022-03-12 09:09:00,2022-03-13 18:34:00,2022-03-13 18:34:00,NaN,2022-03-12 09:53:00,2022-03-13 02:55:00,NaN,2022-03-13 07:40:00,NaN,2022-03-12 15:19:00
5146,5146,67,M,True,2023-11-24 06:47:00,2023-11-24 17:18:00,2023-12-13 10:56:00,2023-11-24 06:59:00,NaN,2023-11-24 19:01:00,2023-12-12 10:16:00,2023-12-12 10:16:00,NaN,NaN,2023-11-25 19:18:00,2023-12-03 12:28:00,2023-11-27 13:26:00,NaN,2023-11-24 18:07:00

In [4]:
df_icu_visit = df_icu[df_icu.isin(['Neurologist Visit']).notna().any(axis=1)].copy()
df_icu_visit

,Patient Id,Age,Gender,Comorbidities,Emergency Dept Time,Admission Time,Discharge Time,CT Scan Time,TPA Time,ICU Arrival Time,ICU Checkout Time,Neurology Ward Arrival Time,Occupational Therapist Visit,Speech Pathologist Visit,Physiotherapist Visit,Dietitian Visit,Social Worker Visit,Cardiologist Visit,Neurologist Visit
1,1,75,F,False,2023-01-04 23:20:00,2023-01-05 02:13:00,2023-01-10 10:59:00,2023-01-04 23:33:00,NaN,2023-01-05 02:14:00,2023-01-06 09:44:00,2023-01-06 09:44:00,NaN,2023-01-07 01:21:00,2023-01-05 03:13:00,NaN,2023-01-06 00:39:00,NaN,2023-01-06 06:17:00
2,2,50,M,False,2022-12-28 18:33:00,2022-12-29 03:20:00,2023-01-06 08:01:00,2022-12-28 18:47:00,NaN,2023-01-01 08:51:00,2023-01-02 22:15:00,2023-01-02 22:15:00,NaN,NaN,NaN,2023-01-06 07:42:00,2023-01-01 04:57:00,NaN,2022-12-29 22:37:00
9,9,58,M,False,2023-06-21 06:56:00,2023-06-21 16:16:00,2023-07-05 11:00:00,2023-06-21 07:06:00,NaN,2023-06-21 18:18:00,2023-06-24 03:17:00,2023-06-24 03:17:00,2023-06-21 18:56:00,NaN,NaN,2023-07-05 10:42:00,2023-06-28 21:08:00,NaN,2023-06-21 16:31:00
13,13,74,M,True,2023-06-30 09:26:00,2023-06-30 19:47:00,2023-07-16 11:11:00,2023-06-30 09:43:00,NaN,2023-06-30 21:34:00,2023-07-12 16:56:00,2023-07-12 16:56:00,2023-07-02 03:18:00,2023-07-01 15:22:00,2023-07-01 11:13:00,NaN,NaN,NaN,2023-06-30 23:17:00
14,14,92,M,False,2022-09-06 05:04:00,2022-09-06 10:17:00,2022-09-24 11:48:00,2022-09-06 05:18:00,NaN,2022-09-09 09:17:00,2022-09-18 08:59:00,2022-09-18 08:59:00,2022-09-08 00:58:00,NaN,2022-09-24 11:13:00,NaN,2022-09-07 23:57:00,NaN,2022-09-08 20:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5139,5139,70,F,False,2022-08-10 19:03:00,2022-08-10 23:34:00,2022-08-18 17:02:00,2022-08-10 19:15:00,2022-08-10 19:54:00,2022-08-11 14:41:00,2022-08-14 00:18:00,2022-08-14 00:18:00,2022-08-11 01:25:00,2022-08-18 16:26:00,2022-08-13 00:06:00,2022-08-12 20:43:00,NaN,NaN,2022-08-11 02:41:00
5142,5142,63,F,True,2022-05-28 16:56:00,2022-05-28 22:01:00,2022-06-10 05:52:00,2022-05-28 17:08:00,NaN,2022-05-28 22:29:00,2022-05-30 01:02:00,2022-05-30 01:02:00,2022-05-29 00:24:00,2022-05-29 04:57:00,NaN,2022-05-30 22:36:00,2022-06-03 22:25:00,2022-06-10 05:20:00,2022-06-04 15:42:00
5144,5144,87,M,True,2023-12-11 00:52:00,2023-12-11 04:36:00,2023-12-18 19:59:00,2023-12-11 01:04:00,NaN,2023-12-11 04:39:00,2023-12-13 18:35:00,2023-12-13 18:35:00,2023-12-11 05:25:00,NaN,2023-12-11 03:54:00,NaN,NaN,NaN,2023-12-12 03:03:00
5145,5145,69,F,False,2022-03-12 00:01:00,2022-03-12 07:49:00,2022-03-20 09:46:00,2022-03-12 00:14:00,NaN,2022-03-12 09:09:00,2022-03-13 18:34:00,2022-03-13 18:34:00,NaN,2022-03-12 09:53:00,2022-03-13 02:55:00,NaN,2022-03-13 07:40:00,NaN,2022-03-12 15:19:00
5146,5146,67,M,True,2023-11-24 06:47:00,2023-11-24 17:18:00,2023-12-13 10:56:00,2023-11-24 06:59:00,NaN,2023-11-24 19:01:00,2023-12-12 10:16:00,2023-12-12 10:16:00,NaN,NaN,2023-11-25 19:18:00,2023-12-03 12:28:00,2023-11-27 13:26:00,NaN,2023-11-24 18:07:00

In [5]:
visits = ['Neurologist Visit', 'Occupational Therapist Visit', 'Speech Pathologist Visit', 'Physiotherapist Visit', 'Dietitian Visit', 'Social Worker Visit', 'Cardiologist Visit']

In [18]:
@interact(Visit=widgets.SelectMultiple(options=visits, value=['Neurologist Visit']), ViewBy=widgets.RadioButtons(options=['Patient Id', 'Age'], value='Patient Id'), Show_Comorbidities=False)
def plot_visits(Visit, ViewBy, Show_Comorbidities):
    fig, ax = plt.subplots()

    if Show_Comorbidities:
        df_icu_visit = df_icu[df_icu['Comorbidities']]

    df_icu_visit = df_icu[df_icu.isin(Visit).notna().any(axis=1)].copy()
    
    for visit in Visit:
        doctor_visit = pd.to_datetime(df_icu_visit[visit])
        icu_time = pd.to_datetime(df_icu_visit['ICU Checkout Time'])

        df_icu_visit[f'Arrival in ICU ({visit})'] = doctor_visit - icu_time


        df_icu_visit.loc[df_icu_visit[f'Arrival in ICU ({visit})'] <= pd.Timedelta(0), f'In ICU ({visit})'] = 'Visit During\nICU Stay'
        df_icu_visit.loc[df_icu_visit[f'Arrival in ICU ({visit})'] > pd.Timedelta(0), f'In ICU ({visit})'] = 'Visit After\nICU Checkout'

    df_icu_visit['Intersection'] = np.nan

    df_icu_visit['Intersection'] = df_icu_visit['Intersection'].astype(object)

    for visit in Visit:
        df_icu_visit.loc[df_icu_visit[f'In ICU ({visit})'] == 'Visit During\nICU Stay', 'Intersection'] = 'Visit During\nICU Stay'
        df_icu_visit.loc[df_icu_visit[f'In ICU ({visit})'] == 'Visit After\nICU Checkout', 'Intersection'] = 'Visit After\nICU Checkout'

    nan_condition = df_icu_visit[[f'In ICU ({visit})' for visit in Visit]].isna().any(axis=1)
    df_icu_visit.loc[nan_condition, 'Intersection'] = np.nan

    project_palette = {'Visit During\nICU Stay': '#CA0016', 'Visit After\nICU Checkout': '#009797'}

    sns.stripplot(data=df_icu_visit, x=ViewBy, y='Intersection', hue='Intersection', s=2, order=['Visit During\nICU Stay', 'Visit After\nICU Checkout'], ax=ax, legend=False, palette=project_palette)

    ax.set_ylabel('')
    ax.set_title('ICU Visits Analysis')

    plt.show()

interactive(children=(SelectMultiple(description='Visit', index=(0,), options=('Neurologist Visit', 'Occupatio…

1. We expected the neurologist visit during ICU time the most but it seems that Neurologist visit after the ICU checkout is also significant.

https://prod.strokebestpractices.ca/recommendations/acute-stroke-management/inpatient-prevention-and-management-of-complications-following-stroke?_ga=2.101666051.384248697.1711740394-1300068819.1711740393

9.6 (iii) - Abnormal results from the initial or ongoing swallowing screens should trigger a prompt referral to a speech-language pathologist, occupational therapist, dietitian, and/or other trained dysphagia clinicians for more detailed assessment and management of swallowing, feeding, nutritional, and hydration status [Strong recommendation; Moderate quality of evidence].

When selecting the Occupational Therapist Visit, Speech Pathalogist Visit and Dietician Visit together and setting x-axis to Age, we came to know that patients from 50 to 90 years are being referred to these physicians during their stay in ICU.

## Attributions

- StripPlot - https://seaborn.pydata.org/generated/seaborn.stripplot.html#seaborn.stripplot
- Indexing Copy - https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy